$('.login_box a').click(function () {
  $(this)
    .toggleClass('active2')
    .siblings()
    .removeClass('active2')
    .end()
    .find('i')
    .toggleClass('active')
    .end()
    .siblings()
    .find('i')
    .removeClass('active')
})
